import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/main.ts', 'src/guard.ts'],
  format: ['esm'],
  dts: true,
  banner: {
    js: '#!/usr/bin/env node',
  },
  splitting: false,
  sourcemap: true,
  clean: true,
  outDir: 'dist',
  target: 'node18',
  platform: 'node',
  external: [
    // Node.js built-ins
    'fs',
    'path',
    'crypto',
    'http',
    'https',
    'http2',
    'net',
    'tls',
    'url',
    'querystring',
    'os',
    'vm',
    'domain',
    'dgram',
    'dns',
    'assert',
    'util',
    'zlib',
    'buffer',
    'stream',
    'events',
    'string_decoder',
    'punycode',
    'module',
    'constants',
    'process',
    'tty',
    'child_process',
    'cluster',
    'readline',
    'repl',
    'v8',
    'async_hooks',
    'perf_hooks',
    'timers',
    'diagnostics_channel',
    'trace_events',
    'console',
    'inspector',
    'worker_threads',
    'wasi',
    'test',
    'node:test',
    'node:fs',
    'node:path',
    'node:readline/promises',
    'node:process'
  ]
})
